version: '2'

services:
  main:
    build: ./src
    command: bash -c "./run.sh"
    volumes: 
      - ./src:/code
      - /var/log/erss:/var/log/erss:rw
    ports:
      - "12345:12345"
    tty: true
